name: CI - Pull Request

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4

            - name: Install dependencies
              run: npm install

            - name: Run lint
              run: npm run lint

            - name: Run tests
              run: npm test

            - name: Build project
              run: npm run build
